services:
  api:
    image: hometaskwebapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Conecta a API ao banco mysql usando o container e as credenciais abaixo
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      # Chave secreta do JWT
      - Jwt__Key=${JWT_SECRET_KEY}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: hometask-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: hometask
    ports:
      - "3307:3306"
    volumes:
      - hometask_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hometask_mysql_data:
