apiVersion: v1
kind: Service
metadata:
  name: hometask-api-service
spec:
  type: LoadBalancer # <- Tipo LoadBalancer pega os pods internos e "joga" pra fora do Cluster Kubernetes
  ports:
    - port: 8080        # Porta que expomos para o navegador
      targetPort: 8080  # A porta lá de dentro do Container do Pod
      nodePort: 30080   # Porta secundária de acesso (caso precise usar IP da maquina invés de localhost)
  selector:
    app: hometask-api