apiVersion: v1
kind: Secret
metadata:
  name: hometask-secrets
type: Opaque
data:
  # A senha '123456789' em base64. O Kubernetes exige que os secrets sejam em base64.
  mysql-root-password: MTIzNDU2Nzg5